import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "../globals.css";
import App from "@/components/App";
import NextTopLoader from "nextjs-toploader";
import SideImage from "@/components/auth/SideImage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-outfit",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} bg-[#fffdf5]  antialiased  flex flex-col mx-auto my-0 max-w-[144rem]`}
      >
        <NextTopLoader color="#121212" height={4} showSpinner={false} />
        <App>
          <div className="flex h-screen">
            <SideImage />

            <main className=" w-full flex items-center justify-center ">
              {children}
            </main>
          </div>
        </App>
      </body>
    </html>
  );
}
