import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import App from "@/components/App";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-outfit",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className}  antialiased  flex flex-col mx-auto my-0 max-w-[144rem]`}
      >
        <App>
          <Header />
          <main className="px-12 py-[65px] min-h-screen">{children}</main>
        </App>
      </body>
    </html>
  );
}
