import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import App from "@/components/App";
import Header from "@/components/layout/Header";
import NextTopLoader from "nextjs-toploader";
import BottomLinks from "@/components/layout/BottomLinks";
import MobileHeader from "@/components/layout/MobileHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-outfit",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} bg-[#fffdf5]  antialiased  flex flex-col mx-auto my-0 max-w-[144rem]`}
      >
        <NextTopLoader color="#121212" height={4} showSpinner={false} />
        <App>
          <div className="hidden lg:block">
            <Header />
          </div>
          <div className="block lg:hidden">
            <MobileHeader />
          </div>
          <main className="lg:mx-12 md:mx-8 mx-4 py-[65px] min-h-screen">
            {children}
          </main>
          <div className="block lg:hidden">
            <BottomLinks />
          </div>
        </App>
      </body>
    </html>
  );
}
