import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "../globals.css";
import App from "@/components/App";
import Header from "@/components/layout/header/Header";
import NextTopLoader from "nextjs-toploader";
import BottomLinks from "@/components/layout/BottomLinks";
import Footer from "@/components/layout/Footer";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/lib/auth";
import { getGuestViaEmail } from "@/lib/action";
import MobileHeader from "@/components/layout/header/MobileHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-outfit",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const guest = session?.user
    ? ((await getGuestViaEmail(session.user.email || "")) as unknown as Guest)
    : null;
  return (
    <html lang="en">
      <body
        className={`${outfit.className} bg-[#fffdf5]  antialiased  flex flex-col mx-auto my-0 max-w-[144rem]`}
      >
        <NextTopLoader color="#121212" height={4} showSpinner={false} />
        <App>
          <div className="hidden lg:block">
            <Header guest={guest} />
          </div>
          <div className="block lg:hidden">
            <MobileHeader />
          </div>
          <main className="lg:mx-12 md:mx-8 mx-4 py-[60px] lg:py-[80px] min-h-screen">
            {children}
          </main>
          <Toaster position="top-center" />
          <div className="block lg:hidden">
            <BottomLinks />
          </div>
          <Footer />
        </App>
      </body>
    </html>
  );
}
